-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 13:53:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema real_estate_website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema real_estate_website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `real_estate_website` DEFAULT CHARACTER SET utf8 ;
USE `real_estate_website` ;

-- -----------------------------------------------------
-- Table `real_estate_website`.`image_cin_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`image_cin_users` (
  `id_images` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `front_image_cin` BLOB NOT NULL,
  `back_image_cin` BLOB NOT NULL,
  PRIMARY KEY (`id_images`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_image_UNIQUE` ON `real_estate_website`.`image_cin_users` (`id_images` ASC) VISIBLE;

CREATE UNIQUE INDEX `front_image_cin_UNIQUE` ON `real_estate_website`.`image_cin_users` (`front_image_cin` ASC) VISIBLE;

CREATE UNIQUE INDEX `back_image_cin_UNIQUE` ON `real_estate_website`.`image_cin_users` (`back_image_cin` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`users` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full name` VARCHAR(30) NOT NULL,
  `email_user` VARCHAR(30) NOT NULL,
  `num_tel` INT(8) UNSIGNED NOT NULL,
  `paswword` VARCHAR(30) NOT NULL,
  `type_user` ENUM('S', 'V') NOT NULL COMMENT 'S means seller \nV means visitor ',
  `creation_date` VARCHAR(45) NOT NULL,
  `creation_date` TIMESTAMP(222) NOT NULL DEFAULT current_timestamp(),
  `image_cin_users_id_images` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_users_image_cin_users`
    FOREIGN KEY (`image_cin_users_id_images`)
    REFERENCES `real_estate_website`.`image_cin_users` (`id_images`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_user_UNIQUE` ON `real_estate_website`.`users` (`id_user` ASC) VISIBLE;

CREATE UNIQUE INDEX `num_tel_UNIQUE` ON `real_estate_website`.`users` (`num_tel` ASC) VISIBLE;

CREATE INDEX `fk_users_image_cin_users_idx` ON `real_estate_website`.`users` (`image_cin_users_id_images` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`city` (
  `idcity` INT NOT NULL AUTO_INCREMENT,
  `citycol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcity`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcity_UNIQUE` ON `real_estate_website`.`city` (`idcity` ASC) VISIBLE;

CREATE UNIQUE INDEX `citycol_UNIQUE` ON `real_estate_website`.`city` (`citycol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`gouverment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`gouverment` (
  `idgouverment` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gouverment` VARCHAR(45) NOT NULL,
  `city_idcity1` INT NOT NULL,
  PRIMARY KEY (`idgouverment`),
  CONSTRAINT `fk_gouverment_city2`
    FOREIGN KEY (`city_idcity1`)
    REFERENCES `real_estate_website`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idgouverment_UNIQUE` ON `real_estate_website`.`gouverment` (`idgouverment` ASC) VISIBLE;

CREATE UNIQUE INDEX `gouverment_UNIQUE` ON `real_estate_website`.`gouverment` (`gouverment` ASC) VISIBLE;

CREATE INDEX `fk_gouverment_city2_idx` ON `real_estate_website`.`gouverment` (`city_idcity1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`adresse_buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`adresse_buildings` (
  `id_adresse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adresse_building` VARCHAR(45) NOT NULL,
  `gouverment_idgouverment1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_adresse`),
  CONSTRAINT `fk_adresse_buildings_gouverment2`
    FOREIGN KEY (`gouverment_idgouverment1`)
    REFERENCES `real_estate_website`.`gouverment` (`idgouverment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_adresse_UNIQUE` ON `real_estate_website`.`adresse_buildings` (`id_adresse` ASC) VISIBLE;

CREATE UNIQUE INDEX `adresse_building_UNIQUE` ON `real_estate_website`.`adresse_buildings` (`adresse_building` ASC) VISIBLE;

CREATE INDEX `fk_adresse_buildings_gouverment2_idx` ON `real_estate_website`.`adresse_buildings` (`gouverment_idgouverment1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`buildings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `surface` FLOAT NOT NULL,
  `forsell_orforrent` ENUM('R', 'S') NOT NULL COMMENT 'R home for rent\nS home for sell\n',
  `adresse_buildings_id_adresse` INT UNSIGNED NOT NULL,
  `upload_date` TIMESTAMP(222) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_buildings_adresse_buildings1`
    FOREIGN KEY (`adresse_buildings_id_adresse`)
    REFERENCES `real_estate_website`.`adresse_buildings` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `real_estate_website`.`buildings` (`id` ASC) VISIBLE;

CREATE INDEX `fk_buildings_adresse_buildings1_idx` ON `real_estate_website`.`buildings` (`adresse_buildings_id_adresse` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`building_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`building_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `real_estate_website`.`building_images` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`user_has_buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`user_has_buildings` (
  `users_id_user` INT UNSIGNED NOT NULL,
  `buildings_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id_user`, `buildings_id`),
  CONSTRAINT `fk_users_has_buildings_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `real_estate_website`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_buildings_buildings1`
    FOREIGN KEY (`buildings_id`)
    REFERENCES `real_estate_website`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_buildings_buildings1_idx` ON `real_estate_website`.`user_has_buildings` (`buildings_id` ASC) VISIBLE;

CREATE INDEX `fk_users_has_buildings_users1_idx` ON `real_estate_website`.`user_has_buildings` (`users_id_user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_website`.`buildings_has_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate_website`.`buildings_has_images` (
  `buildings_id` INT UNSIGNED NOT NULL,
  `building_images_id` INT NOT NULL,
  PRIMARY KEY (`buildings_id`, `building_images_id`),
  CONSTRAINT `fk_buildings_has_building_images_buildings1`
    FOREIGN KEY (`buildings_id`)
    REFERENCES `real_estate_website`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buildings_has_building_images_building_images1`
    FOREIGN KEY (`building_images_id`)
    REFERENCES `real_estate_website`.`building_images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_buildings_has_building_images_building_images1_idx` ON `real_estate_website`.`buildings_has_images` (`building_images_id` ASC) VISIBLE;

CREATE INDEX `fk_buildings_has_building_images_buildings1_idx` ON `real_estate_website`.`buildings_has_images` (`buildings_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
